### ISSUE TITLE
Neuen Tagebucheintrag erfassen

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#11]
Als **Benutzer** möchte ich neue Tagebucheinträge erstellen können, um meine Erlebnisse festzuhalten. Ein Eintrag soll dabei ein Datum, einen Text (bis 1000 Zeichen) und eine Kategorie enthalten.

**Acceptance Criterias**
- Nutzer kann nach dem Einloggen einen Link anklicken um einen neuen Eintrag zu erstellen.
- Nutzer kann ein Datum auswählen, an dem der Eintrag erstellt werden soll.
- Nutzer kann einen Text eingeben, der gespeichert werden soll.
- Nutzer kann eine Kategorie auswählen, zu der der Eintrag gehört.
- Nutzer kann nur seine selbst erstellten Einträge sehen.

**Task**
- [x] Link auf eingeloggter Home-Page anzeigen
- [x] Datumsauswahl Standard auf aktuellen Tag einstellen
- [x] Datumsauswahl änderbar machen
- [x] Texteingabefeld erstellen
- [x] Funktion zum Auflisten von Kategorien erstellen
- [x] Kategorieauswahl via DropDown hinzufügen
- [x] Funktion zum Erstellen von Einträgen erstellen

**Comment by cybrox** [comment]
Abhängig von https://github.com/IBZTI2018/TI3-WT-SA/issues/12

**Comment by glaand** [comment]
https://github.com/IBZTI2018/TI3-WT-SA/commit/dd235b57022f8156a26ad07e71fc1e57f2143c79
https://github.com/IBZTI2018/TI3-WT-SA/commit/f864ba6fd76017b6b999613c75fbed397554edaf
https://github.com/IBZTI2018/TI3-WT-SA/commit/1d898c9b56638175818bc06673d89832774843b8
