### ISSUE TITLE
Kategorien Erstellen

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#12]
Als **Benutzer** möchte ich meinen Tagebucheintrag einer Kategorie zuordnen können, um Ordnung in meinem Tagebuch zu halten.

**Accept Criterias**
- Kategorie-Tabelle existiert und hat Standard-Kategorien

**Tasks**
- [x] Kategorie-Tabelle erstellen in create script
- [x] Kategorie-Tabelle löschen in drop script
- [x] Kategorie-Tabelle füllen mit Beispielen in seed script
- [x] Model für Kategorie schreiben
- [x] Tests für CategoryModel schreiben
