### ISSUE TITLE
Anzeigen von Einträgen

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#15]
Als **Benutzer** möchte ich meine bestehenden Einträge anzeigen können, damit ich mein Tagebuch lesen kann.

**Acceptance Criterias**
- Benutzer kann seine erstellten Einträge einsehen
- Benutzer kann seine erstellten Einträge nicht bearbeiten
- Benutzer kann nur seine eigenen Einträge sehen

**Tasks**
- [x] Funktion zum auflisten aller Einträge eines Benutzers erstellen
- [x] Einträge beim Auflisten nach Datum (absteigend) sortieren
- [x] Einträge anzeigen, wenn der Nutzer eingeloggt ist

**Comment by cybrox** [comment]
Abhängig von https://github.com/IBZTI2018/TI3-WT-SA/issues/11
