### ISSUE TITLE
Nutzerdaten in der Datenbank speichern

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#2]
Als **Systemadministrator** will ich Nutzerdaten in der Datenbank speichern können, um ein Verzeichnis von Tagebuchnutzern anzulegen. Dafür soll für jeden Nutzer mindestens der Benutzername, sowie das Passwort gespeichert werden.

**Acceptance Criterias:**
* Als Systemadministartor kann ich die Datenbank mit einem Setup-Script aufsetzen.
* Als Systemadministrator kann ich einen Benutzer in der Datenbank via `adminer` hinzufügen.
* Es kann kein Benutzername doppelt benutzt werden.

**Tasks**
* [x] SQL-Query für das Erstellen der Benutzertabelle schreiben.
* [x] Unique-Constraint einfügen, damit ein Benutzername eindeutig ist.
* [x] PHP-Script erstellen mit dem die Datenbank aufgesetzt werden kann.
* [x] PHP-Script erstellen mit dem die Datenbank mit Beispielsdaten "geseeded" werden kann.
