### ISSUE TITLE
Anmelden mit Benutzerdaten

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#3]
Als **Endnutzer** möchte ich mich über einen Login-Screen anmelden können, um die Applikation zu nutzen und ein tolles Tagebuch zu schreiben.

**Acceptance Criterias**
* Beim Aufrufen der Applikation erscheint ein Login-Bildschirm.
* Als Benutzer kann ich mich mit meinen Benutzername und Passwort einloggen.
* Als Benutzer möchte ich eine informative Fehlermeldung erhalten, wenn ich falsche Zugangsdaten eingebe.
* Nach erfolgreichem Login möchte ich weiter geleitet werden.

**Tasks**
* [x] PHP-Funktion für das Prüfen von Nutzerdaten in der Datenbank schreiben (Benutzername + Passwort muss in der Datenbank existieren).
* [x] Login-Seite mit minimalistischem Design und Inputs erstellen.
* [x] Leere Seite die durch Authentifizierung geschützt ist erstellen.
* [x] Bei Abschicken des Logins Daten validieren und auf leere Seite weiterleiten.
* [x] Fehlermeldung anzeigen, wenn Validierung fehlschlägt.
