### ISSUE TITLE
Einträge filtern

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#32]
Als **Nutzer** möchte ich meine Einträge nach einem Datumsbereich und ihrer Kategorie filtern können, um alte Einträge einfach wieder zu finden.

**Acceptance Criterias**
- Nutzer kann eine Kategorie auswählen und es werden nur Einträge dieser Kategorie angezeigt.
- Nutzer kann einen Datumsbereich auswählen und es werden nur Einträge zwischen diesen Daten angezeigt.

**Tasks**
- [x] Funktion erstellen um Einträge nach Kategorie zu filtern
- [x] Funktion erstellen um Einträge nach Datumsbereich zu filtern
- [x] Funktion erstellen um Einträge nach Kategorie und Datumsbereich zu filtern
- [x] Filterfelder auf der Eintragsübersicht anzeigen
- [x] Gefilterte Einträge ausgeben
