### ISSUE TITLE
Bilder für Einträge speichern

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#33]
Als **Nutzer** möchte ich meinen Einträgen Bildern hinzufügen können, um mehr Erinnerungen festhalten zu können.

**Acceptance Criterias**
- Beim Erstellen eines Eintrags kann ein Bild hochgeladen werden
- Beim Anzeigen der Einträge werden die Bilder mit angezeigt

**Tasks**
- [x] Datenbank anpassen um Bilder (binary blobs) zu unterstützen
- [x] File-Upload bei Eintragserstellung hinzufügen
- [x] Bild bei Eintragsliste anzeigen

**Comment by cybrox** [comment]
Spent 1h30
