### ISSUE TITLE
Registrieren mit neuen Benutzerdaten

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#4]
Als **neuer Enduser** möchte ich mich registrieren können um mit den bereits bestehenden Benutzern zusammen den Dienst nutzen zu können.

**Acceptance Criterias**:
* Als Nutzer kann ich auf der Login-Seite einen neuen Account erstellen.
* Für das Erstellen eines neuen Accounts muss ich einen Benutzernamen und ein Passwort eingeben.
* Zum Schutz vor Vertippen muss das Passwort zwei mal eingegeben werden.
* Stimmen die Passwörter nicht überein, oder ist ein Feld leer, erscheint eine Fehlermeldung.
* Nach dem Registrieren werde ich wie ein eingeloggter Benutzer auf die interne Seite weitergeleitet.

**Tasks:**
- [x] PHP Funktion zum Prüfen ob ein Benutzer existiert schreiben.
- [x] PHP Funktion zum Erstellen eines neuen Benutzers schreiben.
- [x] Form zur Registrierung auf Login-Seite hinzufügen.
- [x] Benutzer anlegen und weiterleiten, wenn korrekte Daten eingegeben wurden. (Bestehende Login-Weiterleitung verwenden)
- [x] Fehlermeldung anzeigen wenn ein Feld leer ist
- [x] Fehlermeldung anzeigen wenn die Passwörter nicht überein stimmen
- [x] Fehlermeldung anzeigen wenn Benutzername bereits verwendet wird.

**Comment by cybrox** [comment]
spent 1h30m

**Comment by cybrox** [comment]
PR https://github.com/IBZTI2018/TI3-WT-SA/pull/9 has been approved and merged
