### ISSUE TITLE
Design überarbeiten

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#42]
Als **Nutzer** möchte ich ein konsistentes Design um mein Tagebuch voll zu geniessen.

**Acceptance Criterias**
- Alle Komponenten müssen einen einheitlichen Style haben.
- "Handschrift" Font soll nur für Tagebucheinträge verwendet werden
- Cover seite soll in geöffneter Ansicht sichtbar sein.

**Tasks**
- [x] Verbleibende Komponenten stylen
- [x] Style vereinheitlichen
- [x] Offenes Cover hinzufügen
- [x] Offenes Cover auf Mobile verstecken
- [x] Schriftarten korrigieren
