### ISSUE TITLE
Passwörter mit pbkdf2 hashen

### ISSUE THREAD

**Issue by cybrox** [IBZTI2018/TI3-WT-SA#5]
Als **Systemadministrator** will ich, dass Passwörter in der Datenbank nur gehasht gespeichert werden, um unsere Sicherheitsstandards zu erfüllen.

**Acceptance Criterias**:
* Passwörter sind in der Datenbank nur in `pbkdf2` gehashter Form gespeichert.
* Login und Registrierung funktionieren weiterhin.

**Tasks:**
* [x] PHP-Funktion zum hashen von Passwörtern schreiben
* [x] PHP-Funktion zum Prüfen von Benutzerdaten auf pbkdf2 updaten
* [x] PHP-Seed-Script anpassen um Dummy Nutzer mit gehashtem Passwort zu erzeugen.

**Comment by glaand** [comment]
https://github.com/IBZTI2018/TI3-WT-SA/commit/448cccf1fa47f7db45fa2592c8fb96c16b3ee095
