### ISSUE TITLE
FA_1.10 Es kann abgefragt werden, für welche Tage kein Tagebucheinträge vorhanden sind.

### ISSUE THREAD

**Issue by glaand** [IBZTI2018/TI3-WT-SA#53]
Als Benutzer möchte ich wissen an welchen Tagen gemäss Datenbereich ich keine Einträge in meinem Tagebuch habe.

**Acceptance Criterias:**

- Beim Filtern kann eine Checkbox angeklickt werden, um diese Information zusätzlich anzeigen zu lassen.

**Tasks:**
* [x] - Checkbox beim POST abfangen
* [x] - Zusätzliche Query ausführen
* [x] - Daten in der Ergebniss anzeigen lassen
* [x] - Dokumentation anpassen
